### ISSUE TITLE
Add dagger support

### ISSUE THREAD

**Issue by alexandru-calinoiu** [krschultz/android-proguard-snippets#18]
Hi,

Any luck with http://square.github.io/dagger/ ?

**Comment by dallasgutauckis** [comment]
To the best of my knowledge there is no concrete solution due to how Dagger builds the graph/configuration. One has to provide explicit `-keepnames` entries for anything any module `@Provides`.

**Comment by ivazhnov** [comment]
This worked for me
```java
-keep class dagger.** { *; }
-keepclassmembers,allowobfuscation class * {
    @javax.inject.* *;
    @dagger.* *;
    <init>();
}
-keep class **$$ModuleAdapter
-keep class **$$InjectAdapter
-keep class **$$StaticInjection
-keep class javax.inject.** { *; }
-dontwarn dagger.internal.codegen.**
-dontwarn dagger.producers.internal.**
-dontwarn dagger.shaded.auto.common.**
```

**Comment by krschultz** [comment]
I added a Dagger config from another PR. See https://github.com/krschultz/android-proguard-snippets/blob/master/libraries/proguard-square-dagger.pro. If that doesn't work we can revise it, but it was fairly close to what @ivazhnov suggested so worth a shot.
