### ISSUE TITLE
Add Proguard for Jackson JSON Processor

### ISSUE THREAD

**Issue by goonerDroid** [krschultz/android-proguard-snippets#19]
Hey guys do you have any ideas for implementation of Jackson JSON Processor.Would appreciate if you guys included it!

**Comment by goonerDroid** [comment]
@krschultz Finally found my proguard config for Jackson Proccessor.My Config is as follows:-

-keepattributes *Annotation*,EnclosingMethod,Signature
-keepnames class com.fasterxml.jackson.** { *; }
 -dontwarn com.fasterxml.jackson.databind.**
 -keep class org.codehaus.** { *; }
 -keepclassmembers public final enum org.codehaus.jackson.annotate.JsonAutoDetect$Visibility {
 public static final org.codehaus.jackson.annotate.JsonAutoDetect$Visibility *; }
-keep public class your.class.** {
  public void set*(***);
  public *** get*();
}

your.class here is the getter/setter you are using to parse the response

also keep in mind to compile the same versions of Jackson Library.In my case i am using 

    compile 'com.fasterxml.jackson.core:jackson-databind:2.4.2'
    compile 'com.fasterxml.jackson.core:jackson-annotations:2.4.2'
    compile 'com.fasterxml.jackson.core:jackson-core:2.4.2'

**Comment by urvish91** [comment]
-keepnames class com.fasterxml.jackson.** { *; }
-dontwarn com.fasterxml.jackson.databind.*

Just add this and add in gradle this.

   compile 'com.fasterxml.jackson.core:jackson-databind:2.5.3'
    compile 'com.fasterxml.jackson.core:jackson-core:2.5.3'

it will work definitely.

**Comment by goonerDroid** [comment]
Dunno why @krschultz  reopened this issue rules posted by me is working fine!

**Comment by krschultz** [comment]
@goonerDroid I dropped the ball on this. I reopened it at the time because although you posted the config here, we never actually put it into a file in the libraries folder. This is what we currently have:

```
# Proguard configuration for Jackson 2.x (fasterxml package instead of codehaus package)

-keep class com.fasterxml.jackson.databind.ObjectMapper {
    public <methods>;
    protected <methods>;
}
-keep class com.fasterxml.jackson.databind.ObjectWriter {
    public ** writeValueAsString(**);
}
```

**Comment by christhoval06** [comment]
@goonerDroid work fine for me

thanks
