### ISSUE TITLE
Add Timber 4.0.1

### ISSUE THREAD

**Issue by BillZangardi** [krschultz/android-proguard-snippets#75]
https://github.com/JakeWharton/timber

**Comment by Flydiverny** [comment]
Timber shouldn't require any additional proguard rules?

And for required proguard rules it contains a [`consumer-proguard-rules.pro` (link)](https://github.com/JakeWharton/timber/blob/master/timber/consumer-proguard-rules.pro) already including the necessary rules for you :)


`-dontwarn org.jetbrains.annotations.**`

**Comment by krschultz** [comment]
Thanks @Flydiverny, that's really helpful. I think I'm going to close this, whenever a library has consumerProguard files that is the preferred solution. Although it requires an upgrade from 4.0.1 to 4.1.0 that doesn't look too onerous.
